apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailhog-2
  namespace: mailhog-2
spec:
  # maxHistory: 3
  # rollback:
  #   enable: true
  #   retry: true
  #   maxRetries: 3
  # helmVersion: v3
  releaseName: mailhog-2
  targetNamespace: mailhog-2
  interval: 10m
  chart:
    spec:
      chart: mailhog
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: mailhog-repository
        # Optional, defaults to the namespace of the HelmRelease
        namespace: mailhog-2
  # chart:
  #   repository: https://pratikbalar.github.io/myhelmrepo
  #   name: mailhog
  #   version: 1.0.1
  values:
    image:
      repository: mailhog/mailhog
      tag: "v1.0.0"
      pullPolicy: Always

    nameOverride: ""
    fullnameOverride: ""

    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      type: ClusterIP
      port:
        http: 8025
        tcp-smtp: 1025

    securityContext:
      runAsUser: 1000
      fsGroup: 1000
      runAsNonRoot: true

    auth:
      enabled: true
      existingSecret: ""
      fileName: auth.txt
      fileContents: "improwised:$2y$04$rmBFhcM3VpkjU/KHLaQK3eyb2nQ8cbkJXINrhWKPcK1MALtKE7TuS"

    resources:
      limits:
        cpu: 100m
        memory: 400Mi
      requests:
        cpu: 50m
        memory: 64Mi
